#ifndef PHOTO_GALLERY_H
#define PHOTO_GALLERY_H

typedef enum
{
    DISPLAY_NO_SCALE,
    DISPLAY_NO_SCALE_CENTRE,
    DISPLAY_NO_SCALE_CENTRE_X,
    DISPLAY_NO_SCALE_CENTRE_Y,
    DISPLAY_STRETCH,
    DISPLAY_FIXED_RATIO
} DISPLAY_TYPE;

typedef enum
{
    GET_RANDOM_PHOTO,
    GET_SEQUENTIAL_PHOTO
} GET_TYPE;

#endif
